name: Pelican Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run black on content
      run: |
        black content
    
    - name: Generate with Pelican
      run: |
        pelican -D content

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.7.2
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: output # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
